app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # portfolioのurls.pyを読み込み
    path('', include('portfolio.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    # viewsからindexを読み込んで、nameをindexに
    path('', views.index, name='index'),
    path('works', views.works, name='works')
]

portfolio/models.py
from functools import update_wrapper
from django.db import models

# Create your models here.


class Profile(models.Model):

    name = models.CharField('名前', max_length=100)
    image = models.ImageField('イメージ', upload_to='profile')
    career = models.CharField('職業', max_length=55, null=True, blank=True)
    org = models.CharField('所属組織', max_length=55, null=True, blank=True)
    age = models.CharField('年齢', max_length=55, null=True, blank=True)
    twitter = models.URLField('TwitterのURL', null=True, blank=True)
    blog = models.URLField('BlogのURL', null=True, blank=True)
    github = models.URLField('githubのURL', null=True, blank=True)
    introduction = models.TextField('自己紹介文')
    mail = models.CharField('メール', max_length=255)

    class Meta:
        verbose_name_plural = 'プロフィール'


class Description(models.Model):

    text = models.CharField('本文', max_length=255)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'スキルの概要文'


class Skill(models.Model):
    name = models.CharField('名前', max_length=100)
    years = models.FloatField('経験年数', default=0)
    description = models.ForeignKey(
        Description, on_delete=models.SET_NULL, null=True, verbose_name='説明文')

    def years_rounded(self):
        years = self.years
        if years.is_integer():
            years = int(years)
        return years

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'スキル'


class Work(models.Model):

    title = models.CharField('タイトル', max_length=100)
    image = models.ImageField('イメージ', upload_to='works', null=True, blank=True)
    url = models.URLField('URL')
    published = models.DateField('公開日', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '作品'

portfolio/views.py
from django.shortcuts import render
from .models import Profile, Skill, Work


def index(request):

    profile = Profile.objects.all().last()
    skills = Skill.objects.all()
    works = Work.objects.all().order_by('-published')[:3]

    context = {
        'profile': profile,
        'skills': skills,
        'works': works,
    }
    return render(request, 'index.html', context)


def works(request):
    works = Work.objects.all().order_by('-published')
    context = {
        'works': works,
    }
    return render(request, 'works.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link
        href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700&family=Stick&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/portfolio.css' %}">
</head>

<body class="bg-secondary">

    {% block main %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous">
    </script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<header class="header">
    <div class="container">
        <div class="text-center">
            <div class="mb-1">
                <img src="{{ profile.image.url }}" height="180" width="180" class="rounded-circle img-center-cover">
            </div>
            <div>
                <h2 class="text-subtitle header-title mb-3 fw-bold">{{ profile.name }}</h2>
                <div class="mb-3 fw-bold">
                    {% if profile.career %}
                    <span class="text-subtitle">{{ profile.career }}</span>
                    <span class="text-subtitle">/</span>
                    {% endif %}
                    {% if profile.org %}
                    <span class="text-subtitle">{{ profile.org }}</span>
                    {% endif %}
                    {% if profile.age %}
                    <span class="text-subtitle">/</span>
                    <span class="text-subtitle">{{ profile.age }}</span>
                    {% endif %}
                </div>
                <div class="mb-4">
                    {% if profile.twitter %}<a href="{{ profile.twitter }}" target="_blank"><i
                            class="fab fa-twitter sns-icon text-twitter"></i></a>{% endif %}
                    {% if profile.blog %}<a href="{{ profile.blog }}" target="_blank"><i
                            class="fas fa-blog sns-icon text-blog"></i></a>{% endif %}
                    {% if profile.github %}<a href="{{ profile.github }}" target="_blank"><i
                            class="fab fa-github sns-icon text-github"></i></a>{% endif %}
                </div>
                <div class="row">
                    <div class="col-md-8 mx-auto">
                        <div class="intro-box">
                            <P class="text-intro">
                                {{ profile.introduction|safe|linebreaksbr }}
                            </P>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-3">
                    <a href="mailto:{{ profile.mail }}" class="btn btn-dark fw-bold">お問い合わせ</a>
                </div>
            </div>
        </div>
    </div>
    </div>

    </div>
</header>

<section class="mb-100">
    <div class="container text-subtitle">
        <div>
            <h3 class="display-4 fw-bold text-subtitle">SKILLS</h3>
            <div class="row">
                <div class="col-md-10 mx-auto py-4">
                    <table class="table table-borderless">
                        {% for skill in skills %}
                        <tr>
                            <td class="align-middle h4 fw-bold text-subtitle">{{skill.name}}</td>
                            <td class="align-middle"><span
                                    class="badge bg-dark py-1 px-2 font-14">{{skill.years_rounded}}年</span></td>
                            <td class="align-middle text-subtitle">{{skill.description}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mb-5">
    <div class="container">
        <div>
            <h3 class="display-4 fw-bold text-subtitle mb-3">WORKS</h3>
            <div class="row">
                {% for work in works %}
                <div class="col-lg-4 mb-3">
                    <a href="{{ work.url }}" target="_blank">
                        <div class="card shadow-sm border boder-light">
                            <div>
                                <img src="{% if work.image %}{{ work.image.url }}{% else %}{% static 'assets/img/sample.png' %}{% endif %}"
                                    class="w-100 img-center-cover" height="300">
                            </div>
                            <div class="p-3 bg-dark">
                                <h5 class="text-subtitle mb-0">{{work.title}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
                <div class="text-end">
                    <a href="{% url 'portfolio:works' %}" class="btn btn-lg btn-dark">View All Works <i
                            class="fas fa-list-alt ps-1"></i></a>
                </div>
            </div>
        </div>

</section>

{% endblock %}

templates/works.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<section>
    <a href="/" class="left-top btn btn-dark"><i class="fas fa-chevron-left pe-1"></i>Back</a>
    <div class="container">
        <div class="text-center">
            <h3 class="display-4 fw-bold text-subtitle m-3">WORKS</h3>
        </div>
        <div class="row">
            {% for work in works %}
            <div class="col-lg-4 mb-3">
                <a href="{{ work.url }}" target="_blank">
                    <div class="card shadow-sm border boder-light">
                        <div>
                            <img src="{% if work.image %}{{ work.image.url }}{% else %}{% static 'assets/img/sample.png' %}{% endif %}"
                                class="w-100 img-center-cover" height="300">
                        </div>
                        <div class="p-3 bg-dark">
                            <h5 class="text-subtitle mb-0">{{work.title}}</h5>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

</section>

{% endblock %}